
package banque.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Bourse", targetNamespace = "http://banque/ws", wsdlLocation = "file:/home/noureddine/Documents/workspace-sts-3.5.1/WebServiceClient/src/Bourse.wsdl")
public class Bourse
    extends Service
{

    private final static URL BOURSE_WSDL_LOCATION;
    private final static WebServiceException BOURSE_EXCEPTION;
    private final static QName BOURSE_QNAME = new QName("http://banque/ws", "Bourse");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/noureddine/Documents/workspace-sts-3.5.1/WebServiceClient/src/Bourse.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOURSE_WSDL_LOCATION = url;
        BOURSE_EXCEPTION = e;
    }

    public Bourse() {
        super(__getWsdlLocation(), BOURSE_QNAME);
    }

    public Bourse(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOURSE_QNAME, features);
    }

    public Bourse(URL wsdlLocation) {
        super(wsdlLocation, BOURSE_QNAME);
    }

    public Bourse(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOURSE_QNAME, features);
    }

    public Bourse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bourse(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebSBourse
     */
    @WebEndpoint(name = "WebSBoursePort")
    public WebSBourse getWebSBoursePort() {
        return super.getPort(new QName("http://banque/ws", "WebSBoursePort"), WebSBourse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebSBourse
     */
    @WebEndpoint(name = "WebSBoursePort")
    public WebSBourse getWebSBoursePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://banque/ws", "WebSBoursePort"), WebSBourse.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOURSE_EXCEPTION!= null) {
            throw BOURSE_EXCEPTION;
        }
        return BOURSE_WSDL_LOCATION;
    }

}
